name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Environment Varibale File
        run:
          echo -e "REACT_APP_KAKAO_APP_KEY=${{secrets.REACT_APP_KAKAO_APP_KEY}}\n
          REACT_APP_KAKAO_REST_API=${{secrets.REACT_APP_KAKAO_REST_API}}\n" > ./.env

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: fe/build
